language: java

jdk:
  - oraclejdk8

addons:
  firefox: "latest"
      
script:
  - mvn install -Dwebdriverextensions.disabledbrowsers=firefox
  
before_script:
  - export CHROME_BIN=chromium-browser
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start" 
  - "mkdir -p /tmp/webdriverextensions-maven-plugin/cache"
  - "mkdir -p /tmp/webdriverextensions-maven-plugin/drivers"
  - "mkdir -p /tmp/webdriverextensions-maven-plugin/temp"
